Add italian translation
vtex-apps/search pull request #183
Opened 2023-03-28 11:06 UTC by feraraujofilho

The current app does not offer italian translation, and our customer Canali in Italy has requested it.

Therefore, we have added it to the code.

You can test it here: https://fixprojecttasks--canali.myvtex.com/?__bindingAddress=it.canali.com/

2023-03-31 14:32 UTC, camilavcoutinho requested changes

2023-04-03 07:00 UTC, feraraujofilho commented
@camilavcoutinho all changes have been committed. Thanks.

2023-04-03 13:43 UTC, camilavcoutinho approved these changes

2023-04-03 13:43 UTC, camilavcoutinho commented
> @camilavcoutinho all changes have been committed. Thanks.

Awesome! Now you need to ask someone from the search team, to review the PR as well.

2023-04-27 08:56 UTC, feraraujofilho commented
@camilavcoutinho I am not sure who exactly needs to do that. Could you kindly ask directly someone from your product team? 
For us this PR is not urgent anymore since we have fixed directly on the client's account but I believe it is good for VTEX.

2023-05-03 19:52 UTC, thalytafabrine approved these changes

2023-05-03 19:53 UTC, merged